CREATE OR REPLACE FORCE VIEW V_CRS_CATEGORY(
   CATEGORYID,
   LAST_UPDATE,
   NAME,
   NAME_EN
)
AS
   SELECT DEP_CATEGORYID CATEGORYID,
          MODIFYSTAMP LAST_UPDATE,
          NAME,
          NAME_EN
     FROM DEP_CATEGORY
    WHERE RMV = 0
/

CREATE OR REPLACE FORCE VIEW V_CRS_CLIENT(
   VTB_LEGALENTITYID,
   FULL_NAME,
   FULL_NAME_EN,
   NAME,
   NAME_EN,
   OPFID,
   COUNTRYID,
   CATEGORYID,
   SEGMENTID,
   INDUSTRYID,
   LAST_UPDATE
)
AS
   SELECT CG.SLXID VTB_LEGALENTITYID,
          CG.NAME_FULL FULL_NAME,
          CG.NAME_FULL_EN FULL_NAME_EN,
          CG.NAME,
          CG.NAME_EN,
          CG.CL_OPFID OPFID,
          CG.REG_COUNTRYID COUNTRYID,
          CG.DEP_CATEGORYID CATEGORYID,
          CEP.CL_EARN_SEGID SEGMENTID,
          CG.CL_INDUSTRYID INDUSTRYID,
          GREATEST (NVL (CG.MODIFYSTAMP, TO_DATE ('1900', 'YYYY')),
                    NVL (CEP.MODIFYSTAMP, TO_DATE ('1900', 'YYYY')) --,NVL (CE.MODIFYSTAMP, TO_DATE ('1900', 'YYYY'))
                                                                   )
             LAST_UPDATE
     FROM CL_GLOBAL CG
          LEFT JOIN CL_EARN_PREF CEP
             ON CEP.CL_GLOBALID = CG.CL_GLOBALID AND CEP.RMV = 0
    WHERE CG.RMV = 0 AND CG.CL_GLOBAL_CUTID = 1
/

CREATE OR REPLACE FORCE VIEW V_CRS_CLIENT_INN(
   VTB_LEGALENTITYID,
   TAXID,
   COUNTRYID,
   LAST_UPDATE
)
AS
   SELECT CG.SLXID VTB_LEGALENTITYID,
          CGP.PR_VALUE TAXID,
          CGP.COUNTRYISOID COUNTRYID,
          CGP.MODIFYSTAMP LAST_UPDATE
     FROM CL_GLOBAL_PR CGP
          INNER JOIN CL_GLOBAL CG
             ON     CG.CL_GLOBALID = CGP.CL_GLOBALID
                AND CGP.RMV = 0
                AND CG.RMV = 0
                AND CG.CL_GLOBAL_CUTID = 1
    WHERE CGP.CL_PR_TYPEID = 1
/

CREATE OR REPLACE FORCE VIEW V_CRS_CLIENT_OGRN
(
   VTB_LEGALENTITYID,
   REG_NUM,
   COUNTRYID,
   LAST_UPDATE
)
AS
   SELECT CG.SLXID VTB_LEGALENTITYID,
          CGP.PR_VALUE REG_NUM,
          CGP.COUNTRYISOID COUNTRYID,
          CGP.MODIFYSTAMP LAST_UPDATE
     FROM CL_GLOBAL_PR CGP
          INNER JOIN CL_GLOBAL CG
             ON     CG.CL_GLOBALID = CGP.CL_GLOBALID
                AND CGP.RMV = 0
                AND CG.RMV = 0
                AND CG.CL_GLOBAL_CUTID = 1
    WHERE CGP.CL_PR_TYPEID = 2
/

CREATE OR REPLACE FORCE VIEW V_CRS_CLIENT_TYPE(
   VTB_LEGALENTITYID,
   CLIENT_TYPEID,
   ORGID,
   LAST_UPDATE
)
AS
   SELECT CG.SLXID VTB_LEGALENTITYID,
          CVPP.CL_TYPEID CLIENT_TYPEID,
          CVP.VTB_ORGID ORGID,
          GREATEST (NVL (CVP.MODIFYSTAMP, TO_DATE ('1900', 'YYYY')),
                    NVL (CVPP.MODIFYSTAMP, TO_DATE ('1900', 'YYYY')))
             LAST_UPDATE
     FROM CL_GLOBAL CG
          INNER JOIN CL_VTBPART CVP
             ON     CVP.CL_GLOBALID = CG.CL_GLOBALID
                AND CVP.RMV = 0
                AND CG.RMV = 0
          INNER JOIN CL_VTBPART_PRECOUNT CVPP
             ON CVP.CL_VTBPARTID = CVPP.CL_VTBPARTID AND CVPP.RMV = 0
    WHERE CG.CL_GLOBAL_CUTID = 1
/

CREATE OR REPLACE FORCE VIEW V_CRS_CLIENT_TYPE_DICT(
   CLIENT_TYPEID,
   LAST_UPDATE,
   NAME,
   NAME_EN,
   PRIORITY
)
AS
   SELECT CL_TYPEID CLIENT_TYPEID,
          MODIFYSTAMP LAST_UPDATE,
          NAME,
          NAME_EN,
          PRIORITY
     FROM CL_TYPE
    WHERE RMV = 0
/

CREATE OR REPLACE FORCE VIEW V_CRS_COUNTRY(
   COUNTRYID,
   LAST_UPDATE,
   CODE_A2,
   CODE_A3,
   NUM_CODE,
   NAME,
   NAME_EN
)
AS
   SELECT COUNTRYISOID COUNTRYID,
          MODIFYSTAMP LAST_UPDATE,
          CODE_A2,
          CODE_A3,
          NUM_CODE,
          NAME,
          NAME_EN
     FROM COUNTRYISO
    WHERE RMV = 0
/

CREATE OR REPLACE FORCE VIEW V_CRS_CURRENCY(
   CURRENCYID,
   LAST_UPDATE,
   CODE_NUM,
   CODE,
   NAME,
   NAME_EN
)
AS
   SELECT CURRENCYISOID CURRENCYID,
          MODIFYSTAMP LAST_UPDATE,
          CODE_NUM,
          CODE,
          NAME,
          NAME_EN
     FROM CURRENCYISO
    WHERE RMV = 0
/

CREATE OR REPLACE FORCE VIEW V_CRS_DEPARTMENT(
   DEPARTMENTID,
   DEP_NAME,
   DEP_NAME_EN,
   DEP_FULL_NAME,
   DEP_FULL_NAME_EN,
   PARENT_DEPARTMENTID,
   LAST_UPDATE
)
AS
   SELECT DD.DEPARTMENTID DEPARTMENTID,
          DD.NAME DEP_NAME,
          DD.NAME_EN DEP_NAME_EN,
          DD.FULL_NAME DEP_FULL_NAME,
          DD.FULL_NAME_EN DEP_FULL_NAME_EN,
          DL.PARENTID PARENT_DEPARTMENTID,
          GREATEST (NVL (DD.MODIFYSTAMP, TO_DATE ('1900', 'YYYY')),
                    NVL (DL.MODIFYSTAMP, TO_DATE ('1900', 'YYYY')))
             LAST_UPDATE
     FROM DEPARTMENT DD
          LEFT JOIN DEP_LINK DL
             ON     DD.DEPARTMENTID = DL.DEPARTMENTID
                AND DL.RMV = 0
                AND DL.DEP_LINK_TYPEID = 1
    WHERE DD.RMV = 0
/

CREATE OR REPLACE FORCE VIEW V_CRS_DEP_CL_HIERARCHY(
   DEPARTMENTID,
   PARENTID,
   LAST_UPDATE
)
AS
   SELECT DEPARTMENTID, PARENTID, MODIFYSTAMP
     FROM DEP_LINK
    WHERE DEP_LINK_TYPEID = 2 AND PARENTID IS NOT NULL
/


CREATE OR REPLACE FORCE VIEW V_CRS_DEP_REG_HIERARCHY(
   DEPARTMENTID,
   PARENTID,
   LAST_UPDATE
)
AS
   SELECT DEPARTMENTID, PARENTID, MODIFYSTAMP
     FROM DEP_LINK
    WHERE DEP_LINK_TYPEID = 3 AND PARENTID IS NOT NULL
/

CREATE OR REPLACE FORCE VIEW V_CRS_GROUP(
   GROUP_ID,
   NAME,
   NAME_EN,
   FULL_NAME,
   FULL_NAME_EN,
   DESCRIPTION,
   DESCRIPTION_EN,
   IS_VTB_DAUGHTER,
   SEGMENTID,
   INDUSTRYID,
   COUNTRYID,
   LAST_UPDATE
)
AS
   SELECT CG.SLXID GROUP_ID,
          CG.NAME,
          CG.NAME_EN,
          CG.NAME_FULL FULL_NAME,
          CG.NAME_FULL_EN FULL_NAME_EN,
          CGD.DESCRIPTION,
          CGD.DESCRIPTION_EN,
          CGP.VALUE IS_VTB_DAUGHTER,
          CEP.CL_EARN_SEGID SEGMENTID,
          CG.CL_INDUSTRYID INDUSTRYID,
          CG.REG_COUNTRYID COUNTRYID,
          GREATEST (NVL (CG.MODIFYSTAMP, TO_DATE ('1900', 'YYYY')),
                    NVL (CEP.MODIFYSTAMP, TO_DATE ('1900', 'YYYY')) --,NVL (CE.MODIFYSTAMP, TO_DATE ('1900', 'YYYY'))
                                                                   )
             LAST_UPDATE
     FROM CL_GLOBAL CG
          LEFT JOIN CL_EARN_PREF CEP
             ON CEP.CL_GLOBALID = CG.CL_GLOBALID AND CEP.RMV = 0
          LEFT JOIN CL_GLOBAL_DESC CGD
             ON CGD.CL_GLOBALID = CG.CL_GLOBALID AND CGD.RMV = 0
          LEFT JOIN CL_GLOBAL_PARAM CGP
             ON     CGP.CL_GLOBALID = CG.CL_GLOBALID
                AND CGP.RMV = 0
                AND CGP.CL_PARAM_TYPEID = 13
    WHERE CG.RMV = 0 AND CG.CL_GLOBAL_CUTID IN (2, 3)
/

CREATE OR REPLACE FORCE VIEW V_CRS_GROUP_PARTICIPANT(
   GROUP_ID,
   VTB_LEGALENTITYID,
   LAST_UPDATE
)
AS
   SELECT CG_P.SLXID GROUP_ID,
          CG.SLXID VTB_LEGALENTITYID,
          GREATEST (NVL (CG_P.MODIFYSTAMP, TO_DATE ('1900', 'YYYY')),
                    NVL (CG.MODIFYSTAMP, TO_DATE ('1900', 'YYYY')))
             LAST_UPDATE
     FROM CL_GLOBAL CG_P
          INNER JOIN CL_GLOBAL CG
             ON     CG_P.CL_GLOBALID = CG.PARENTID
                AND CG_P.RMV = 0
                AND CG.RMV = 0
/

CREATE OR REPLACE FORCE VIEW V_CRS_INDUSTRY(
   INDUSTRYID,
   LAST_UPDATE,
   NAME,
   NAME_EN
)
AS
   SELECT CL_INDUSTRYID INDUSTRYID,
          MODIFYSTAMP LAST_UPDATE,
          NAME,
          NAME_EN
     FROM CL_INDUSTRY
    WHERE RMV = 0
/

CREATE OR REPLACE FORCE VIEW V_CRS_LOCK(
   VTB_LEGALENTITYID,
   DEPARTMENTID,
   LOCK_TYPEID,
   LAST_UPDATE
)
AS
   SELECT CG.SLXID VTB_LEGALENTITYID,
          CL.DEPARTMENTID DEPARTMENTID,
          CL.LOCK_TYPEID LOCK_TYPEID,
          CL.MODIFYSTAMP LAST_UPDATE
     FROM CL_GLOBAL CG
          INNER JOIN CL_VTBPART CVP
             ON     CG.CL_GLOBALID = CVP.CL_GLOBALID
                AND CG.RMV = 0
                AND CVP.RMV = 0
          INNER JOIN CL_LOCK CL
             ON CL.CL_VTBPARTID = CVP.CL_VTBPARTID AND CL.RMV = 0
    WHERE CL.LOCK_TYPEID IN (1, 2, 4)
/


CREATE OR REPLACE FORCE VIEW V_CRS_OPF(
   OPFID,
   COUNTRYID,
   NAME,
   NAME_EN,
   LAST_UPDATE
)
AS
   SELECT CL_OPFID OPFID,
          COUNTRYISOID COUNTRYID,
          NAME,
          NAME_EN,
          MODIFYSTAMP LAST_UPDATE
     FROM CL_OPF
    WHERE RMV = 0
/

CREATE OR REPLACE FORCE VIEW V_CRS_SEGMENT(
   SEGMENTID,
   LAST_UPDATE,
   NAME,
   NAME_EN,
   DIAP_MIN,
   DIAP_MAX,
   CURRENCYID
)
AS
   SELECT CL_EARN_SEGID SEGMENTID,
          MODIFYSTAMP LAST_UPDATE,
          NAME,
          NAME_EN,
          DIAP_MIN,
          DIAP_MAX,
          CURRENCYID
     FROM CL_EARN_SEG
    WHERE RMV = 0
/

CREATE OR REPLACE FORCE VIEW V_CRS_VLE_DELETED(
   VTB_LEGALENTITYID,
   DEL_DATE
)
AS
   SELECT SLXID VTB_LEGALENTITYID, MODIFYSTAMP DEL_DATE
     FROM CL_GLOBAL
    WHERE RMV = 1 AND CL_GLOBAL_CUTID = 1
/

CREATE OR REPLACE FORCE VIEW V_CRS_VLE_DUPLICATE(
   VTB_LEGAL_MOVEMENTSID,
   VTB_LEGALENTITYID_OLD,
   VTB_LEGALENTITYID_NEW,
   ORIGINAL_DATE
)
AS
   SELECT VTB_LEGAL_MOVEMENTSID,
          VTB_LEGALENTITYID_OLD,
          VTB_LEGALENTITYID_NEW,
          ORIGINAL_DATE
     FROM SYSDBA.VTB_LEGAL_MOVEMENTS
    WHERE     VTB_LEGALENTITYID_OLD <> VTB_LEGALENTITYID_NEW
          AND REASON = 'Слияние дубликатов ЕК'
/
